scrape_configs:
  - job_name: 'MonitoringConnectionTestService'
    scrape_interval: 5s # Poll every 5 seconds for a more responsive demo.
    static_configs:
      - targets: ["monitoringconnectiontestservice:8080"]
